name: Build Python Application Release

on:
  push:
    branches: ['main']
  workflow_dispatch:
  release:
    types: [created]  # Trigger on release creation

permissions:
  contents: write

jobs:
  build-windows:
    name: Build Windows Executable
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pygame pymunk
        if (Test-Path requirements.txt) { pip install -r requirements.txt }

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --name python-ragdoll `
                    --onefile `
                    --windowed `
                    main.py

    - name: Package executable
      shell: pwsh
      run: |
        Compress-Archive -Path dist/python-ragdoll.exe -DestinationPath PythonRagdoll-windows.zip

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_name: PythonRagdoll-windows.zip
        asset_path: ./PythonRagdoll-windows.zip
        asset_content_type: application/zip
